# Generated by Django 3.1.5 on 2021-02-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('host_team', models.CharField(max_length=250)),
                ('host_team_score', models.IntegerField(default=0)),
                ('guest_team_score', models.IntegerField(default=0)),
                ('guest_team', models.IntegerField(default=0)),
            ],
        ),
    ]
