# Generated by Django 3.1.5 on 2021-02-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-match_number',)},
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
