# Generated by Django 3.1.5 on 2021-02-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210227_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guest_team',
            field=models.CharField(max_length=250),
        ),
    ]
