# Generated by Django 3.1.5 on 2021-02-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210227_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='guest_team_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='host_team_logo',
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='host_team_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
