# Generated by Django 3.1.5 on 2021-02-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210228_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='surname',
        ),
    ]
