# Generated by Django 3.1.5 on 2021-02-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210228_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directory',
            new_name='Squad',
        ),
    ]
