# Generated by Django 3.1.5 on 2021-02-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_player_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('goal_scored', models.IntegerField(default=0)),
                ('goal_recieved', models.IntegerField(default=0)),
            ],
        ),
    ]
