# Generated by Django 3.1.5 on 2021-02-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_league_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='league_team',
            new_name='LeagueTeam',
        ),
    ]
